# Coding Session 02 · Lab W2



## Today's plan

- Read and clean text; convert types.
- Inspect, merge, filter, group, and create columns in the existing student/score tables.
- Use line breaks to make code easy to read.



### 1. String methods and `.replace()`

`text.replace(old, new)` returns a new string. Save that result if you want to use the corrected text; the original remains unchanged. By default, all occurrences are replaced.


In [1]:
original_sentence = "I love pythn programming."
corrected_sentence = original_sentence.replace("pythn", "Python")
print("Original: " + original_sentence)
print("Corrected: " + corrected_sentence)

Original: I love pythn programming.
Corrected: I love Python programming.



#### Other useful string methods

While `.replace()` is powerful, many other string methods are equally important for text manipulation:

- `.upper()` / `.lower()`: Convert string to uppercase/lowercase.
- `.strip()`: Remove leading/trailing whitespace.
- `.split()`: Split a string into a list of substrings based on a delimiter.
- `.find()` / `.index()`: Find the first occurrence of a substring.
- `.startswith()` / `.endswith()`: Check if a string starts/ends with a specified prefix/suffix.

Some useful examples:

.strip() returns a new string with spaces, tabs, and newlines removed from both ends (not the middle).



In [2]:
raw_text = "  \n  Ada Lovelace \t  "
clean_text = raw_text.strip()
print(clean_text)        # 'Ada Lovelace'


Ada Lovelace



## 2. Converting to and from strings (type casting)

In Python, every piece of data has a specific *type*. For instance, `5` is an integer (`int`), `3.14` is a floating-point number (`float`), and `"hello"` is a string (`str`). Understanding data types is fundamental because different types behave differently and support different operations. For example, you can perform arithmetic operations on numbers, but not directly on strings (e.g., `"5" + "2"` results in `"52"`, not `7`).

**Type casting** (or type conversion) is the process of converting a value from one data type to another. This is a very common operation, especially when dealing with user input (which is often read as a string) or when preparing data for specific operations.



### Check the type before converting: `type()`

Use the built-in `type(value)` to ask Python what kind of object you have. The result `<class 'str'>` means “this value is a string.” Here, *class* is Python's term for the object's type; you do not need to write your own class.

Numbers inside quotation marks are text. Inspecting a type does not change the value.


In [3]:
print(type("25"))   # Text: str
print(type(25))     # Whole number: int
print(type(25.0))   # Decimal number: float
print(type(True))   # True/False value: bool
print(type([25]))   # Collection: list

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'list'>


### Converting to a string (`str()`)

The `str()` function is used to convert values of other data types into strings. This is particularly useful when you want to concatenate (join) numbers or other data with text, or when you need to store non-string data in a text-based format.

#### Converting numbers to strings

Let's say you want to display a message that includes a numerical value.



In [5]:
age = 20
print("I am " + str(age) + " years old.")


I am 20 years old.



### Converting from a string (`int()`, `float()`)

Conversely, you often receive data as strings (e.g., from user input, file reading, or web scraping) that you need to treat as numbers. Python provides `int()` for converting to integers and `float()` for converting to floating-point numbers.

Consider a scenario where a user inputs their age or a price.



In [6]:
user_age_str = "25"
user_age_int = int(user_age_str)
print("User's age (as integer): " + str(user_age_int) + ", Type: " + str(type(user_age_int)))

item_price_str = "19.99"
item_price_float = float(item_price_str)
print("Item price (as float): " + str(item_price_float) + ", Type: " + str(type(item_price_float)))

# You can now perform arithmetic operations
total_cost = item_price_float * 2
print("Total cost for two items: " + str(total_cost))


User's age (as integer): 25, Type: <class 'int'>
Item price (as float): 19.99, Type: <class 'float'>
Total cost for two items: 39.98


## 3. Importing modules and functions

`import math` makes the module available; use its functions with a prefix, as in `math.sqrt(64)`. An alias such as `import pandas as pd` gives a short, consistent name. Importing a library does not load a dataset.


In [7]:
import math
print(math.sqrt(64))


8.0


## 4. Merging data

In real-world data analysis, information is rarely confined to a single table or file. Often, you'll encounter scenarios where relevant data is spread across multiple sources, and you need to combine them to gain a complete picture. The process of combining data based on common columns or keys is known as **merging** or **joining**.

While NumPy is excellent for numerical operations on single arrays, for structured data (like tables with columns and rows, similar to spreadsheets), the **Pandas** library is the go-to tool in Python. Pandas builds on NumPy and provides powerful data structures like `DataFrame`s, which are ideal for tabular data.



### Introduction to Pandas `DataFrame` (brief)

A Pandas `DataFrame` can be thought of as a spreadsheet or a SQL table. It's a 2-dimensional labeled data structure with columns of potentially different types. You can create DataFrames from dictionaries, lists of lists, or by reading data from files (CSV, Excel, etc.). We’ll be using pandas throughout the course, so you’ll have plenty of chances to learn more.



### The `pd.merge()` function

The `pd.merge()` function is the primary way to combine DataFrames based on common columns. It's conceptually similar to SQL JOIN operations.

**Syntax:** `pd.merge(left, right, on=None, how='inner')`

- `left`: The first DataFrame to merge.
- `right`: The second DataFrame to merge.
- `on`: (Optional) Column or list of columns to join on. If `None`, it defaults to the intersection of column names in `left` and `right`.
- `how`: (Optional) Type of merge to be performed. Common types include:
    - `'inner'` (default): Use intersection of keys from both frames.
    - `'left'` (left outer join): Use keys from left frame.
    - `'right'` (right outer join): Use keys from right frame.
    - `'outer'` (full outer join): Use union of keys from both frames.

**Tip (very important):** The column name(s) specified in `on` must exist with the same name in both DataFrames. If the key names differ, the merge will not succeed.



### See which rows each merge keeps

![Merge diagram using the student tables below. Inner keeps IDs 101, 103 and 104; left also keeps 102 with a missing score; right also keeps 105 with a missing name; outer keeps all five IDs.](https://raw.githubusercontent.com/albertostefanelli/DSPC_coding_sessions/master/wk02_observational_claims/assets/merging_student_tables.png)

Match rows by `student_id`, then use `how` to decide which keys remain. The colors track the same IDs across the inputs and outputs. `NaN` marks a missing value, not a score of zero.

#### Inner merge

Let's say we have two DataFrames: one with student IDs and names, and another with student IDs and their scores. We want to combine them to get student names along with their scores.



In [8]:
import pandas as pd

# DataFrame 1: Student Names
students_df = pd.DataFrame({
  "student_id": [101, 102, 103, 104],
  "name": ["Alice", "Bob", "Charlie", "David"]
})

# DataFrame 2: Student Scores
scores_df = pd.DataFrame({
  "student_id": [101, 103, 104, 105],
  "score": [85, 92, 78, 95]
})

print("Students DataFrame:")
print(students_df)
print("\nScores DataFrame:")
print(scores_df)

# Perform an inner merge
merged_df_inner = pd.merge(students_df, scores_df, on="student_id", how="inner")
print("\nInner Merged DataFrame (only common student_ids):")
print(merged_df_inner)


Students DataFrame:
   student_id     name
0         101    Alice
1         102      Bob
2         103  Charlie
3         104    David

Scores DataFrame:
   student_id  score
0         101     85
1         103     92
2         104     78
3         105     95

Inner Merged DataFrame (only common student_ids):
   student_id     name  score
0         101    Alice     85
1         103  Charlie     92
2         104    David     78


### Readable line breaks

Parentheses let one call span several lines without changing its result. Put one argument on each line so you can inspect a join key, change an option, or spot missing punctuation. The multiline dictionaries above follow the same idea.

| Four different uses of space and line breaks |
| :--- |
| **Continuation indentation:** spaces inside parentheses organize arguments; they do not create a new block. |
| **Block indentation:** the indented lines after `if` or `for` belong to that block; indentation changes what Python runs. |
| **Blank lines:** separate logical steps in code. In Markdown, a blank line starts a new paragraph. |
| **Printed line breaks:** `\n` inside a string starts a new output line, as in the table labels above. |


In [9]:
readable_merge = pd.merge(
    students_df,
    scores_df,
    on="student_id",
    how="inner",
)
assert readable_merge.equals(merged_df_inner)
readable_merge


,student_id,name,score
0,101,Alice,85
1,103,Charlie,92
2,104,David,78


### Inspect, select, filter, and create columns

`.shape` reports rows and columns; selecting a list of column names keeps those columns. A Boolean condition selects rows. `.copy()` makes the filtered table independent before we add columns. Here a score is measured out of 100; dividing by 100 changes its unit to a proportion.


In [10]:
print("Rows and columns:", readable_merge.shape)
print(readable_merge.dtypes)
selected = readable_merge[["name", "score"]]
high_scores = readable_merge.loc[readable_merge["score"] >= 80].copy()
high_scores["score_fraction"] = high_scores["score"] / 100
high_scores["points_above_80"] = high_scores["score"] - 80
high_scores


Rows and columns: (3, 3)
student_id    int64
name            str
score         int64
dtype: object


,student_id,name,score,score_fraction,points_above_80
0,101,Alice,85,0.85,5
1,103,Charlie,92,0.92,12


### Grouped means using the same table

Create a group from the existing scores, then calculate its mean. This demonstrates `groupby` syntax; a high-score group having a higher mean is true by construction and supplies no causal evidence. Missing scores must not silently become failures.


In [11]:
comparison = pd.merge(students_df, scores_df, on="student_id", how="left")
comparison["scored_at_least_80"] = comparison["score"].ge(80).astype("boolean")
comparison.loc[comparison["score"].isna(), "scored_at_least_80"] = pd.NA
comparison.groupby("scored_at_least_80", dropna=False)["score"].agg(
    mean_score="mean", observed_scores="count"
)


,mean_score,observed_scores
scored_at_least_80,,
False,78.0,1
True,88.5,2
<NA>,NaN,0


**Practice — write the code:** starting from `readable_merge`, select names and scores below 90, create `points_to_100`, then print the mean score. Explain why using the left merge would require a missing-value decision. The lab applies these operations to campaign data; these toy tables do not reproduce its observational audit.


In [12]:
# Your code: select, filter, create a column, then summarize.



#### Left, right, and outer merges

The `how` argument dictates which keys to include in the merged DataFrame:

-   **Left Merge (`how='left'`):** Includes all rows from the left DataFrame and matching rows from the right. If there's no match in the right DataFrame, `NaN` (Not a Number) is filled for the columns from the right DataFrame.
-   **Right Merge (`how='right'`):** Includes all rows from the right DataFrame and matching rows from the left. If there's no match in the left DataFrame, `NaN` is filled for the columns from the left DataFrame.
-   **Outer Merge (`how='outer'`):** Includes all rows from both DataFrames. Where there are no matching values, `NaN` is filled.

**Tip** The logic of merge can be tricky to remember at first. If you’re unsure, use `help(pd.merge)` to quickly check how it works.




## Error Safari

**1. Wrong data type**



In [13]:
number = 2025

# Bad: AttributeError (int has no attribute 'replace')
# wrong = number.replace("2", "9")

# Good: Convert the integer to a string first
fixed = str(number).replace("2", "9")
print(fixed)     # '9095'


9095



**2. Adding strings instead of numbers**




In [14]:
num1 = "5"
num2 = "2"

# Bad: This doesn’t crash, but it gives the wrong result
wrong_sum = num1 + num2
print(wrong_sum)   # '52' instead of 7

# Good: Convert strings to integers first
right_sum = int(num1) + int(num2)
print(right_sum)   # 7


52
7



**3. Converting an invalid string to a number**




In [15]:
price_str = "19.99 dollars"

# Bad: ValueError (invalid literal for int/float)
# price_num = float(price_str)

# Good: Remove the nonnumeric unit before converting
price_str_clean = "19.99"
price_num = float(price_str_clean)
print(price_num * 2)   # 39.98


39.98


**4. Strings are immutable**

Calling a string method returns a new string. Reassign the variable or save the result under a new name.


In [16]:
msg = "hello world"

#bad: expecting msg to change
msg.replace("world", "Python")
print(msg)   # still "hello world" !

# Good: assign the result to a new variable
new_msg = msg.replace("world", "Python")
print(new_msg)


hello world
hello Python



**5. Key names differ in pd.merge**




In [17]:
students_df = pd.DataFrame({
    "student_id": [101, 102, 103],
    "name": ["Alice", "Bob", "Charlie"]
})

scores_df = pd.DataFrame({
    "id": [101, 103, 104],
    "score": [85, 92, 78]
})

# Bad KeyError (student_id not found in right DataFrame)
# merged = pd.merge(students_df, scores_df, on="student_id")

# Good #1: Rename the column

scores_df_r = scores_df.rename(columns={"id": "student_id"})
merged_1 = pd.merge(students_df, scores_df_r, on="student_id")
print(merged_1)

# Good #2: use left_on / right_on
merged_2 = pd.merge(students_df, scores_df, left_on="student_id", right_on="id")
print(merged_2)



   student_id     name  score
0         101    Alice     85
1         103  Charlie     92
   student_id     name   id  score
0         101    Alice  101     85
1         103  Charlie  103     92



**6. Using the wrong merge type**



In [18]:
students_df = pd.DataFrame({
    "student_id": [101, 102],
    "name": ["Alice", "Bob"]
})
scores_df = pd.DataFrame({
    "student_id": [201, 202],
    "score": [85, 90]
})

# Bad: Inner merge gives empty DataFrame (no common IDs)
merged_inner = pd.merge(students_df, scores_df, on="student_id", how="inner")
print(merged_inner)   # Empty!

# Good: Use outer merge if you want to keep all data
merged_outer = pd.merge(students_df, scores_df, on="student_id", how="outer")
print(merged_outer)


Empty DataFrame
Columns: [student_id, name, score]
Index: []
   student_id   name  score
0         101  Alice    NaN
1         102    Bob    NaN
2         201    NaN   85.0
3         202    NaN   90.0



## Exercise: merges and missing rows

Practice merging two DataFrames with `pd.merge`, and understand how how='left', 'right', and 'outer' change the result. Answer these questions (you do not need any coding for answering these):

- In the left merge, why does student_id=102 have score=NaN?
- In the right merge, why does student_id=105 have name=NaN?
- In the outer merge, which IDs came from only one side?
- How many rows are perfect matches (non-missing name and score)?



In [19]:
students_df = pd.DataFrame({
  "student_id": [101, 102, 103, 104],
  "name": ["Alice", "Bob", "Charlie", "David"]
})
scores_df = pd.DataFrame({
  "student_id": [101, 103, 104, 105],
  "score": [85, 92, 78, 95]
})

# Left merge
merged_df_left = pd.merge(students_df, scores_df, on="student_id", how="left")
print("\nLeft Merged DataFrame (all students from left, matching scores):")
print(merged_df_left)

# Right merge
merged_df_right = pd.merge(students_df, scores_df, on="student_id", how="right")
print("\nRight Merged DataFrame (all scores from right, matching students):")
print(merged_df_right)

# Outer merge
merged_df_outer = pd.merge(students_df, scores_df, on="student_id", how="outer")
print("\nOuter Merged DataFrame (all students and all scores):")
print(merged_df_outer)



Left Merged DataFrame (all students from left, matching scores):
   student_id     name  score
0         101    Alice   85.0
1         102      Bob    NaN
2         103  Charlie   92.0
3         104    David   78.0

Right Merged DataFrame (all scores from right, matching students):
   student_id     name  score
0         101    Alice     85
1         103  Charlie     92
2         104    David     78
3         105      NaN     95

Outer Merged DataFrame (all students and all scores):
   student_id     name  score
0         101    Alice   85.0
1         102      Bob    NaN
2         103  Charlie   92.0
3         104    David   78.0
4         105      NaN   95.0



**Answers:**

- Because 102 exists only in students_df (left table) and not in scores_df, so score is missing.
- Because 105 exists only in scores_df (right table) and not in students_df, so name is missing.
- From left only: 102. From right only: 105.
- 3 rows: IDs 101, 103, 104.



# Congratulations!

You are done with the coding session. Questions or suggestions? Email Alberto at alberto.stefanelli@yale.edu.

